// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbunclqkkouaateopoqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhidW5jbHFra291YWF0ZW9wb3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTA5MTAsImV4cCI6MjA4NTg4NjkxMH0.aNn9Mzr4e6WOFGacAlNzCa-RpUW2t2xB9Qb7bVurnvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});